language: android
sudo: required
jdk: oraclejdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
env:
  global:
    - ANDROID_API_LEVEL=27
    - EMULATOR_API_LEVEL=23
    - ADB_INSTALL_TIMEOUT=15
    - ANDROID_ABI=armeabi-v7a
    
android:
  components:
    - tools
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
    - addon-google_apis-google-23
    - sys-img-x86_64-google_apis-23
    - build-tools-26.0.1
    - android-27

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"

before_install:
  - touch /home/travis/.android/repositories.cfg
  - which sdkmanager
  - yes | sdkmanager --update
  - yes | sdkmanager "system-images;android-23;google_apis;x86_64"
  - yes | sdkmanager "build-tools;27.0.1"
  - yes | sdkmanager "build-tools;27.0.3"
  - yes | sdkmanager --licenses
  - which avdmanager
  - sdkmanager --list
  - touch keystore.properties
  - echo "FOOD2FORK_API_KEY="\"$FOOD2FORK_API_KEY\""" >> keystore.properties
  - chmod +x gradlew
  - "./gradlew dependencies || true"

script:
  - "./gradlew clean build jacocoDebugReport --stacktrace"

before_deploy:
  - git config --local user.name "Amadeu Cavalcante"
  - git config --local user.email "amadeu01@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - cp $TRAVIS_BUILD_DIR/app/debug.keystore $HOME
  - cd app/build/outputs/apk/release/
  - ls -all
  - echo $ANDROID_HOME
  - "${ANDROID_HOME}/build-tools/27.0.1/zipalign -v 4 app-release-unsigned.apk Ingredisearch.apk"

deploy:
  provider: releases
  file: Ingredisearch.apk
  skip_cleanup: true
  description: "Deployed by travis-ci"

  on:
    repo: amadeu01/ingredisearch
    tags: true
    jdk: oraclejdk8
  api_key:
    secure: "mOq3vQeTK8IXLAAB8TC0V58Blp9Ql7cIKAY1gmLws20uRPyWMxhLZPkU3OuEnwTt7/Eya94IetFqx+HKc2bqV9tvTk5KXJjqNcn2V8zHub65I+WqmfbQTM3JrIuyTEQXr6bnRKqghFhKhKSGBI+w37RWSQ5kIAh5qShg9mBNbSs7ZP7OkC5+eNJgQT1OHnufDrjrhks4M5CNGqWgK6vZhb7AHg8e5ay8uwF6Ax4+mh8qsSJOi+VGgz5DDNbx9vg/pOZbWPP+wA1Nwx+SSsSF2Gb4WgreF7tXScDPupd0ABkMcsS/j6aIDqgCFrFMz/0xW8tQeVV6qityFJTay5mVZp6SdMztjKl1Np1ezeWGe2ZUpBnNjmCZEmiwpWOjW2KnpixHBudkQHyF2HMGgZ0jDkDog2PFC39A6hCBRx2o72O7PaHKVTvLAliIVnmsaL38QFqmTDAiuiu8t+nbauEdJazABe+Q41W4USBD7IL/N/KjcKVY15uRHrGSIYOMgItnVBY/3TFWgNji7e9FIcIw+j2T44fv7ZZ6q+uhOcobxHZXQ8OI4aVFL3agUpmH+YFi5ZBayqagWjSmqu8Ct75PrwX1uG5DDspC6PvxVN7QxDSBT97No4WDPNxtcUK0WBkX/eHMCv+drSX4yo5moZdNtnTR3eoz+QMRevmikI1uT2o="

after_success:
  - bash <(curl -s https://codecov.io/bash)
